In [72]:
import pandas as pd
data = pd.read_csv('heart.csv')

In [73]:
data.sample(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
350,66,1,0,120,302,0,0,151,0,0.4,1,0,2,1
518,49,1,2,120,188,0,1,139,0,2.0,1,3,3,0
590,74,0,1,120,269,0,0,121,1,0.2,2,1,2,1
256,35,0,0,138,183,0,1,182,0,1.4,2,0,2,1
100,43,0,2,122,213,0,1,165,0,0.2,1,0,2,1

In [74]:
data.shape

(1025, 14)

In [75]:
X = data.iloc[:,0:-2]
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca
0,52,1,0,125,212,0,1,168,0,1.0,2,2
1,53,1,0,140,203,1,0,155,1,3.1,0,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1
4,62,0,0,138,294,1,1,106,0,1.9,1,3

In [76]:
y = data.iloc[:,-1]
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [77]:
from sklearn.model_selection import train_test_split

In [78]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=23)

In [79]:
print(X_train.shape)
print(X_test.shape)

(820, 12)
(205, 12)

In [80]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [81]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [82]:
clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)

C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [83]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [84]:
from sklearn.metrics import accuracy_score

In [85]:
print("Logisgtic Accuracy: ", 100* accuracy_score(y_test, y_pred1))
print("Decision tree Accuracy: ", 100* accuracy_score(y_test, y_pred2))

Logisgtic Accuracy:  85.85365853658537
Decision tree Accuracy:  100.0

In [86]:
from sklearn.metrics import confusion_matrix

In [88]:
print("Logistic confusion matrix:\n", confusion_matrix(y_test, y_pred1))
print("Decision tree confusion matrix:\n", confusion_matrix(y_test, y_pred1))

Logistic confusion matrix:
 [[79 21]
 [ 8 97]]
Decision tree confusion matrix:
 [[79 21]
 [ 8 97]]

# confusion matrix for multiclass problem

In [89]:
mnist = pd.read_csv("mnist.csv")

In [90]:
mnist.sample(5)

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
21271,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40021,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19390,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33085,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11137,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [91]:
mnist.shape

(42000, 785)

In [92]:
X = mnist.iloc[:, 1:]
y = mnist.iloc[:, 0]

In [93]:
X.shape

(42000, 784)

In [94]:
y.shape

(42000,)

In [95]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=23)

In [96]:
lr = LogisticRegression()
dt = DecisionTreeClassifier()

In [97]:
lr.fit(X_train, y_train)
dt.fit(X_train, y_train)

C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [98]:
y_pred3 = lr.predict(X_test)
y_pred4 = dt.predict(X_test)

In [99]:
print("Logisgtic Accuracy: ", 100* accuracy_score(y_test, y_pred3))
print("Decision tree Accuracy: ", 100* accuracy_score(y_test, y_pred4))

Logisgtic Accuracy:  91.42857142857143
Decision tree Accuracy:  85.6547619047619

In [100]:
print("Logistic confusion matrix:\n\n",
pd.DataFrame(confusion_matrix(y_test, y_pred3), columns=list(range(0,10))))

Logistic confusion matrix:

      0    1    2    3    4    5    6    7    8    9
0  825    0    2    1    3    7    8    3    4    0
1    0  894    4    5    1    3    2    0   14    1
2    3    9  763   17    3    9   15   10   23    5
3    4    5   22  777    0   30    4    4   22   11
4    3    4    4    1  756    2    6    2    5   27
5    5    5    3   30    5  649   19    5   16    7
6    4    0    8    1    5   13  800    3    2    1
7    1    3   12    4   10    2    0  789    4   33
8    3   18   10   27    5   36    4    2  671   15
9    4    1    1   16   27    7    0   29    6  756

In [101]:
print("Decision tree confusion matrix:\n\n", 
pd.DataFrame(confusion_matrix(y_test, y_pred4), columns=list(range(0,10))))

Decision tree confusion matrix:

      0    1    2    3    4    5    6    7    8    9
0  772    2    5    8    4   18   16    5   14    9
1    1  874   11    4    4    7    8    5    8    2
2    6   10  711   30   15   10   19   14   27   15
3   11    7   33  693   14   46    5   13   38   19
4    3    5   11   13  677    6   12    9   19   55
5    6    7    4   31    9  621   19    4   25   18
6   16    2   10    3   12   25  755    0   12    2
7    5    7   16   14   10    2    1  766    8   29
8   13   18   29   24   14   36   16   11  609   21
9    3    5   14   11   36   16    3   30   12  717