In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.impute import MissingIndicator, SimpleImputer

In [4]:
df = pd.read_csv("train.csv", usecols=["Age", "Fare", "Survived"])

In [5]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [6]:
df.shape

(891, 3)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Age       714 non-null    float64
 2   Fare      891 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 21.0 KB

In [8]:
df.isnull().mean()*100

Survived     0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [9]:
X = df.drop("Survived", axis = 1)
y = df["Survived"]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=43)

In [11]:
X_train.head()

      Age      Fare
826   NaN   56.4958
838  32.0   56.4958
763  36.0  120.0000
189  36.0    7.8958
109   NaN   24.1500

In [12]:
si = SimpleImputer()
X_train_trf  = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
clf = LogisticRegression()

In [15]:
clf.fit(X_train_trf, y_train)

LogisticRegression()

In [17]:
y_pred = clf.predict(X_test_trf)

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
print(accuracy_score(y_test, y_pred))

0.6536312849162011

In [20]:
mi = MissingIndicator()

In [21]:
mi.fit(X_train)

MissingIndicator()

In [22]:
X_train_miss = mi.fit_transform(X_train)
X_test_miss = mi.transform(X_test)

In [26]:
mi.features_

array([0], dtype=int64)

In [23]:
X_train["Age_NA"] = X_train_miss

In [24]:
X_test["Age_NA"] = X_test_miss

In [27]:
X_train.head()

      Age      Fare  Age_NA
826   NaN   56.4958    True
838  32.0   56.4958   False
763  36.0  120.0000   False
189  36.0    7.8958   False
109   NaN   24.1500    True

In [28]:
si = SimpleImputer()

In [29]:
X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [30]:
clf = LogisticRegression()

In [31]:
clf.fit(X_train_trf2, y_train)

LogisticRegression()

In [33]:
y_pred = clf.predict(X_test_trf2)

In [34]:
accuracy_score(y_test, y_pred)

0.659217877094972

In [35]:
si = SimpleImputer(add_indicator=True)

In [36]:
X_train_trf3 = si.fit_transform(X_train)
X_test_trf3 = si.transform(X_test)

In [37]:
clf = LogisticRegression()

In [38]:
clf.fit(X_train_trf3, y_train)

LogisticRegression()

In [39]:
y_pred = clf.predict(X_test_trf3)

In [40]:
accuracy_score(y_test, y_pred)

0.659217877094972