In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, precision_score, confusion_matrix

In [2]:
df = pd.read_csv("heart.csv")

In [5]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [6]:
df.shape

(303, 14)

In [12]:
X = df.iloc[:,0:13]
y = df.iloc[:,13]

In [10]:
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=23)

In [15]:
X_train.shape, X_test.shape

((242, 13), (61, 13))

In [24]:
rf = RandomForestClassifier()
gb = GradientBoostingClassifier()
lor = LogisticRegression()
svm = SVC()

In [22]:
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test, y_pred)

0.819672131147541

In [25]:
gb.fit(X_train, y_train)
y_pred = gb.predict(X_test)
accuracy_score(y_test, y_pred)

0.8032786885245902

In [26]:
lor.fit(X_train, y_train)
y_pred = lor.predict(X_test)
accuracy_score(y_test, y_pred)

C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.819672131147541

In [27]:
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
accuracy_score(y_test, y_pred)

0.7213114754098361

In [28]:
#Now we will check it by using cross validation

In [35]:
np.mean(cross_val_score(rf, X, y, cv=10, scoring="accuracy"))

0.824731182795699

In [37]:
np.mean(cross_val_score(lor, X, y, cv=10, scoring="accuracy"))

C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.8316129032258065

In [45]:
rf = RandomForestClassifier(max_samples=0.75, bootstrap=True, random_state=23)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test, y_pred)

0.819672131147541

In [46]:
np.mean(cross_val_score(rf, X, y, cv=10, scoring="accuracy"))

0.8180645161290323

# Hyperparameter Tuning

## GridSearchCV

In [62]:
# Number of decision trees
n_estimators = [20, 50, 100, 150]

# number of features to be consider at evry split
max_features = 0.2, [0.5, 0.75, 0.85, 1]

# number of samples 
max_samples = [0.5, 0.75, 1.0]

# depth of trees 
max_depth = [2, 8, None]

In [63]:
params = {
    "n_estimators" : n_estimators,
    "max_features" : max_features,
    "max_samples" : max_samples,
    "max_depth" : max_depth,
}
print(params)

{'n_estimators': [20, 50, 100, 150], 'max_features': (0.2, [0.5, 0.75, 0.85, 1]), 'max_samples': [0.5, 0.75, 1.0], 'max_depth': [2, 8, None]}

In [64]:
rf = RandomForestClassifier()

In [65]:
rf_grid = GridSearchCV(estimator=rf, param_grid=params, cv=5, verbose=2, n_jobs=-1)

In [66]:
rf_grid.fit(X_train, y_train)

Fitting 5 folds for each of 72 candidates, totalling 360 fits

C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\externals\loky\process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py:542: FitFailedWarning:
180 fits failed out of a total of 360.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
48 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py", line 890, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 1344, in wrapper
    estimator._validate_params()
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got [0.5, 0.75, 0.85, 1] instead.

--------------------------------------------------------------------------------
132 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py", line 890, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 1344, in wrapper
    estimator._validate_params()
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got [0.5, 0.75, 0.85, 1] instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [0.82636054 0.83894558 0.85127551 0.83903061 0.83486395 0.82253401
 0.83052721 0.84302721 0.83069728 0.83061224 0.84294218 0.83494898
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.81377551 0.83894558 0.83044218 0.85943878 0.83894558 0.83486395
 0.84685374 0.81411565 0.81819728 0.83061224 0.84294218 0.84285714
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.84702381 0.82244898 0.84302721 0.84294218 0.79345238 0.81437075
 0.83069728 0.83477891 0.81403061 0.84311224 0.84719388 0.83477891
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan]
  warnings.warn(

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [2, 8, None],
                         'max_features': (0.2, [0.5, 0.75, 0.85, 1]),
                         'max_samples': [0.5, 0.75, 1.0],
                         'n_estimators': [20, 50, 100, 150]},
             verbose=2)

In [67]:
rf_grid.best_params_

{'max_depth': 8, 'max_features': 0.2, 'max_samples': 0.5, 'n_estimators': 150}

In [68]:
rf_grid.best_score_

0.8594387755102041

In [61]:
# raf = RandomForestClassifier(n_estimators=20, max_samples=0.75, max_depth=2, max_features=0.2, random_state=23)
# raf.fit(X_train, y_train)
# y_pred = raf.predict(X_test)
# accuracy_score(y_test, y_pred)

0.8688524590163934

In [69]:
raf = RandomForestClassifier(n_estimators=150, max_samples=0.5, max_depth=8, max_features=0.2, random_state=23)
raf.fit(X_train, y_train)
y_pred = raf.predict(X_test)
accuracy_score(y_test, y_pred)

0.8032786885245902

# RandomSearchCV

In [70]:
# Number of decision trees
n_estimators = [20, 50, 100, 150]

# number of features to be consider at evry split
max_features = 0.2, [0.5, 0.75, 0.85, 1]

# number of samples 
max_samples = [0.5, 0.75, 1.0]

# depth of trees 
max_depth = [2, 8, None]

# bootstrap samples
bootstrap = [True, False]

# minimum samples required to split a node
min_samples_split = [2, 5]

# min samples reuired at each leaf node
min_samples_leaf = [1, 2]

In [71]:
params = {
    "n_estimators" : n_estimators,
    "max_features" : max_features,
    "max_samples" : max_samples,
    "max_depth" : max_depth,
    "bootstrap" : bootstrap,
    "min_samples_split" : min_samples_split,
    "min_samples_leaf" : min_samples_leaf
}
print(params)

{'n_estimators': [20, 50, 100, 150], 'max_features': (0.2, [0.5, 0.75, 0.85, 1]), 'max_samples': [0.5, 0.75, 1.0], 'max_depth': [2, 8, None], 'bootstrap': [True, False], 'min_samples_split': [2, 5], 'min_samples_leaf': [1, 2]}

In [72]:
rf = RandomForestClassifier()
rf_grid = GridSearchCV(estimator=rf, param_grid=params, cv=5, verbose=2, n_jobs=-1)

In [73]:
rf_grid.fit(X_train, y_train)

Fitting 5 folds for each of 576 candidates, totalling 2880 fits

C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py:542: FitFailedWarning:
2160 fits failed out of a total of 2880.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
925 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py", line 890, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 1344, in wrapper
    estimator._validate_params()
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got [0.5, 0.75, 0.85, 1] instead.

--------------------------------------------------------------------------------
515 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py", line 890, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 1344, in wrapper
    estimator._validate_params()
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got [0.5, 0.75, 0.85, 1] instead.

--------------------------------------------------------------------------------
720 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py", line 890, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 1351, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_forest.py", line 433, in fit
    raise ValueError(
ValueError: `max_sample` cannot be set if `bootstrap=False`. Either switch to `bootstrap=True` or set `max_sample=None`.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [0.81428571 0.83061224 0.84302721 0.83894558 0.78903061 0.81003401
 0.83469388 0.85544218 0.82219388 0.83877551 0.82236395 0.83477891
 0.79804422 0.82661565 0.83477891 0.83886054 0.80144558 0.83894558
 0.84319728 0.83894558 0.81411565 0.81428571 0.82653061 0.82661565
 0.84268707 0.83452381 0.83078231 0.82244898 0.81853741 0.85110544
 0.84727891 0.84302721 0.80986395 0.83069728 0.82236395 0.83069728
 0.79353741 0.83886054 0.83894558 0.84302721 0.81411565 0.81828231
 0.85535714 0.83477891 0.81003401 0.83052721 0.83460884 0.83477891
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.83886054 0.83477891 0.84710884 0.84302721 0.83486395 0.82227891
 0.84294218 0.83078231 0.81785714 0.83469388 0.83477891 0.83903061
 0.80994898 0.85127551 0.83052721 0.85110544 0.80969388 0.84294218
 0.83477891 0.83477891 0.83035714 0.83078231 0.83894558 0.82661565
 0.82661565 0.82253401 0.84294218 0.83477891 0.83061224 0.83477891
 0.82244898 0.84302721 0.80187075 0.82644558 0.83486395 0.84710884
 0.81828231 0.85119048 0.84294218 0.83069728 0.79336735 0.82253401
 0.82653061 0.84294218 0.84294218 0.83469388 0.83886054 0.85544218
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.81811224 0.83886054 0.84311224 0.84702381 0.77687075 0.83486395
 0.83052721 0.83886054 0.81403061 0.84702381 0.84719388 0.83486395
 0.82661565 0.83078231 0.84710884 0.83078231 0.80595238 0.82627551
 0.83052721 0.83894558 0.81003401 0.84311224 0.83469388 0.82661565
 0.82210884 0.81411565 0.83886054 0.85136054 0.80178571 0.84319728
 0.83069728 0.84302721 0.80960884 0.82644558 0.84302721 0.82661565
 0.81828231 0.83886054 0.84302721 0.83052721 0.82236395 0.83486395
 0.83477891 0.84302721 0.79362245 0.84693878 0.83903061 0.83069728
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan]
  warnings.warn(

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'bootstrap': [True, False], 'max_depth': [2, 8, None],
                         'max_features': (0.2, [0.5, 0.75, 0.85, 1]),
                         'max_samples': [0.5, 0.75, 1.0],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [20, 50, 100, 150]},
             verbose=2)

In [74]:
rf_grid.best_params_

{'bootstrap': True,
 'max_depth': 2,
 'max_features': 0.2,
 'max_samples': 0.5,
 'min_samples_leaf': 1,
 'min_samples_split': 5,
 'n_estimators': 150}

In [75]:
rf_grid.best_score_

0.8554421768707483