In [1]:
import pandas as pd
import numpy as np

In [32]:
date = pd.read_csv("orders.csv")
time = pd.read_csv("messages.csv")

# first working on the orders data for dates

In [33]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [34]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [35]:
# we need to change the datatype of the date column object to datetime

In [36]:
date["date"] = pd.to_datetime(date["date"])

In [37]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [38]:
date.sample(5)

          date  product_id  city_id  orders
39  2019-05-12        2376       16       1
926 2019-07-07        6640       26      48
544 2018-08-01        3222       25       7
762 2018-08-12        5058        2       2
673 2019-01-25        6215       22       8

# 1. Extract year

In [39]:
date["year"] = date["date"].dt.year

In [40]:
date.head()

        date  product_id  city_id  orders  year
0 2019-12-10        5628       25       3  2019
1 2018-08-15        3646       14     157  2018
2 2018-10-23        1859       25       1  2018
3 2019-08-17        7292       25       1  2019
4 2019-01-06        4344       25       3  2019

# 2. Extract month

In [41]:
date["month"] = date["date"].dt.month

In [42]:
date.head()

        date  product_id  city_id  orders  year  month
0 2019-12-10        5628       25       3  2019     12
1 2018-08-15        3646       14     157  2018      8
2 2018-10-23        1859       25       1  2018     10
3 2019-08-17        7292       25       1  2019      8
4 2019-01-06        4344       25       3  2019      1

In [43]:
date["month_name"] = date["date"].dt.month_name()

In [44]:
date.sample(4)

          date  product_id  city_id  orders  year  month month_name
57  2019-08-04        2837       18     370  2019      8     August
767 2019-11-30        5117       27       2  2019     11   November
359 2019-03-23        3339       22      38  2019      3      March
37  2018-08-18        4436       17       2  2018      8     August

# 3. Extract day

In [45]:
date["day"] = date["date"].dt.day

In [46]:
date.head()

        date  product_id  city_id  orders  year  month month_name  day
0 2019-12-10        5628       25       3  2019     12   December   10
1 2018-08-15        3646       14     157  2018      8     August   15
2 2018-10-23        1859       25       1  2018     10    October   23
3 2019-08-17        7292       25       1  2019      8     August   17
4 2019-01-06        4344       25       3  2019      1    January    6

In [52]:
# day of week
date["day_dow"] = date["date"].dt.dayofweek

In [53]:
date.sample(5)

,date,product_id,city_id,orders,year,month,month_name,day,day_name,day_dow
957,2019-07-12,5250,3,9,2019,7,July,12,4,4
406,2018-11-20,1081,22,1,2018,11,November,20,1,1
443,2018-09-21,873,25,16,2018,9,September,21,4,4
842,2018-07-23,2190,14,3,2018,7,July,23,0,0
501,2019-01-24,1881,14,14,2019,1,January,24,3,3

In [55]:
date.drop(columns=["day_name"], inplace=True)

In [57]:
date.sample(3)

,date,product_id,city_id,orders,year,month,month_name,day,day_dow
754,2019-05-03,2323,25,122,2019,5,May,3,4
972,2019-11-08,5282,4,6,2019,11,November,8,4
692,2019-02-18,7419,16,1,2019,2,February,18,0

In [58]:
# day of week name
date["day_name"] =date["date"].dt.day_name()

In [59]:
date.sample(4)

,date,product_id,city_id,orders,year,month,month_name,day,day_dow,day_name
224,2019-11-20,4495,28,2,2019,11,November,20,2,Wednesday
418,2019-07-16,3553,0,1,2019,7,July,16,1,Tuesday
853,2019-08-11,7430,1,1,2019,8,August,11,6,Sunday
369,2019-01-02,2357,14,60,2019,1,January,2,2,Wednesday

In [60]:
# day is weekend or not?
date["weekend"] = np.where(date["day_name"].isin(["Saturday", "Sunday"]),1, 0)

In [61]:
date.head()

,date,product_id,city_id,orders,year,month,month_name,day,day_dow,day_name,weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

In [62]:
# Extracting week of the year (there are 52 or 53 weeks in a year)

In [148]:
date["date_week"] = date["date"].dt.isocalendar().week

In [149]:
date.head()

,date,product_id,city_id,orders,year,month,month_name,day,day_dow,day_name,weekend,quarter,semester,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,4,2,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,3,2,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,4,2,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,3,2,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1

In [88]:
# Extracting the quarter of the year

In [89]:
date["quarter"] = date["date"].dt.quarter

In [90]:
date.head()

,date,product_id,city_id,orders,year,month,month_name,day,day_dow,day_name,weekend,quarter
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

In [91]:
# Extract Semester

In [92]:
date["semester"] = np.where(date["quarter"].isin([1,2]), 1, 2)

In [95]:
date.sample(3)

,date,product_id,city_id,orders,year,month,month_name,day,day_dow,day_name,weekend,quarter,semester
566,2019-04-29,3646,14,63,2019,4,April,29,0,Monday,0,2,1
967,2019-06-11,6093,28,1,2019,6,June,11,1,Tuesday,0,2,1
601,2019-11-24,6592,25,12,2019,11,November,24,6,Sunday,1,4,2

# Extract time elapsed between dates

In [96]:
import datetime

In [97]:
today = datetime.datetime.today()

In [98]:
today

datetime.datetime(2024, 2, 5, 12, 25, 33, 573172)

In [100]:
today-date["date"].head()

0   1518 days 12:25:33.573172
1   2000 days 12:25:33.573172
2   1931 days 12:25:33.573172
3   1633 days 12:25:33.573172
4   1856 days 12:25:33.573172
Name: date, dtype: timedelta64[ns]

In [101]:
date.head()

,date,product_id,city_id,orders,year,month,month_name,day,day_dow,day_name,weekend,quarter,semester
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

In [102]:
(today-date["date"]).dt.days

0      1518
1      2000
2      1931
3      1633
4      1856
       ...
995    1946
996    1887
997    1735
998    1800
999    1574
Name: date, Length: 1000, dtype: int64

In [126]:
np.round((today-date["date"]) / np.timedelta64(1 ,"h"), 0)

0      36444.0
1      48012.0
2      46356.0
3      39204.0
4      44556.0
        ...
995    46716.0
996    45300.0
997    41652.0
998    43212.0
999    37788.0
Name: date, Length: 1000, dtype: float64

# Now working on the message dataset to extact the time

In [127]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [128]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [129]:
time["date"] = pd.to_datetime(time["date"])

In [130]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [131]:
time["hour"] = time["date"].dt.hour

In [132]:
time.head()

                 date                                                msg  hour
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37     0
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826    23
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576     0
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...     0
4 2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше    23

In [133]:
time["min"] = time["date"].dt.minute
time["sec"] = time["date"].dt.second

In [134]:
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [135]:
# Extract time part

In [136]:
time["time"] = time["date"].dt.time

In [137]:
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [138]:
# Time difference

In [139]:
today - time["date"]

0     3704 days 11:35:33.573172
1     3568 days 12:45:33.573172
2     4054 days 12:04:33.573172
3     3356 days 11:54:33.573172
4     3753 days 13:14:33.573172
                 ...
995   4343 days 11:35:33.573172
996   3664 days 13:11:33.573172
997   4129 days 12:48:33.573172
998   4245 days 12:51:33.573172
999   3517 days 13:00:33.573172
Name: date, Length: 1000, dtype: timedelta64[ns]

In [140]:
# in seconds

In [141]:
np.round((today-time["date"]) / np.timedelta64(1 ,"s"), 0)

0      320067334.0
1      308321134.0
2      350309074.0
3      290001274.0
4      324306874.0
          ...
995    375276934.0
996    316617094.0
997    356791714.0
998    366814294.0
999    303915634.0
Name: date, Length: 1000, dtype: float64

In [142]:
# in minutes

In [143]:
np.round((today-time["date"]) / np.timedelta64(1 ,"m"), 0)

0      5334456.0
1      5138686.0
2      5838485.0
3      4833355.0
4      5405115.0
         ...
995    6254616.0
996    5276952.0
997    5946529.0
998    6113572.0
999    5065261.0
Name: date, Length: 1000, dtype: float64

In [144]:
# in hours

In [145]:
np.round((today-time["date"]) / np.timedelta64(1 ,"h"), 0)

0       88908.0
1       85645.0
2       97308.0
3       80556.0
4       90085.0
         ...
995    104244.0
996     87949.0
997     99109.0
998    101893.0
999     84421.0
Name: date, Length: 1000, dtype: float64

In [147]:
import pandas as pd

# Create a DataFrame with a datetime column
data = {'timestamp': ['2024-02-01', '2024-02-10', '2024-03-15']}
df = pd.DataFrame(data)

# Convert the 'timestamp' column to datetime format
df['timestamp'] = pd.to_datetime(df['timestamp'])

# Access the week number using the dt accessor
df['week_number'] = df['timestamp'].dt.isocalendar().week

# Print the DataFrame with the week number
print(df)

   timestamp  week_number
0 2024-02-01            5
1 2024-02-10            6
2 2024-03-15           11

In [150]:
np.round((today-time["date"]) / np.timedelta64(1 ,"M"), 0)

ValueError: Unit M is not supported. Only unambiguous timedelta values durations are supported. Allowed units are 'W', 'D', 'h', 'm', 's', 'ms', 'us', 'ns'