In [30]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [31]:
df = pd.read_csv("train.csv", usecols=["Survived","Age", "Pclass", "SibSp", "Parch"])

In [32]:
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [33]:
df.dropna(inplace=True)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 714 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  714 non-null    int64
 1   Pclass    714 non-null    int64
 2   Age       714 non-null    float64
 3   SibSp     714 non-null    int64
 4   Parch     714 non-null    int64
dtypes: float64(1), int64(4)
memory usage: 33.5 KB

In [35]:
X = df.iloc[:, 1:]
y = df.iloc[:, 0]

In [36]:
X.head()

   Pclass   Age  SibSp  Parch
0       3  22.0      1      0
1       1  38.0      1      0
2       3  26.0      0      0
3       1  35.0      1      0
4       3  35.0      0      0

In [37]:
cross_val_score(LogisticRegression(), X, y, scoring="accuracy", cv=20).mean()

0.6933333333333332

# Applying feature construction

In [38]:
X["Family_size"] = X["SibSp"] + X["Parch"] + 1

In [39]:
X.head()

   Pclass   Age  SibSp  Parch  Family_size
0       3  22.0      1      0            2
1       1  38.0      1      0            2
2       3  26.0      0      0            1
3       1  35.0      1      0            2
4       3  35.0      0      0            1

In [40]:
def myfam(num):
    if num == 1: # alone
        return 0
    elif num > 1 and num <= 4: # small family
        return 1
    elif num > 4: # large family
        return 2

In [41]:
myfam(5)

2

In [42]:
X["Family_type"] = X["Family_size"].apply(myfam)

In [44]:
X.sample(5)

     Pclass   Age  SibSp  Parch  Family_size  Family_type
386       3   1.0      5      2            8            2
649       3  23.0      0      0            1            0
353       3  25.0      1      0            2            1
139       1  24.0      0      0            1            0
395       3  22.0      0      0            1            0

In [45]:
X.drop(columns=["SibSp", "Parch", "Family_size"], inplace=True)

In [46]:
X.head()

   Pclass   Age  Family_type
0       3  22.0            1
1       1  38.0            1
2       3  26.0            0
3       1  35.0            1
4       3  35.0            0

In [48]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring="accuracy", cv=20))

0.7003174603174602

# Feature Splitting

In [49]:
df = pd.read_csv("train.csv")

In [50]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [51]:
df["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [60]:
df["Name"].str.split(",", expand=True)[1].str.split(".", expand=True)[0]

0         Mr
1        Mrs
2       Miss
3        Mrs
4         Mr
       ...
886      Rev
887     Miss
888     Miss
889       Mr
890       Mr
Name: 0, Length: 891, dtype: object

In [61]:
df["Title"] = df["Name"].str.split(",", expand=True)[1].str.split(".", expand=True)[0]

In [62]:
df[["Title", "Name"]]

     Title                                               Name
0       Mr                            Braund, Mr. Owen Harris
1      Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2     Miss                             Heikkinen, Miss. Laina
3      Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4       Mr                           Allen, Mr. William Henry
..     ...                                                ...
886    Rev                              Montvila, Rev. Juozas
887   Miss                       Graham, Miss. Margaret Edith
888   Miss           Johnston, Miss. Catherine Helen "Carrie"
889     Mr                              Behr, Mr. Karl Howell
890     Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [66]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr

In [75]:
df.groupby(["Title"])["Survived"].mean().sort_values(ascending = False)

Title
 the Countess    1.000000
 Mlle            1.000000
 Sir             1.000000
 Ms              1.000000
 Lady            1.000000
 Mme             1.000000
 Mrs             0.792000
 Miss            0.697802
 Master          0.575000
 Col             0.500000
 Major           0.500000
 Dr              0.428571
 Mr              0.156673
 Jonkheer        0.000000
 Rev             0.000000
 Don             0.000000
 Capt            0.000000
Name: Survived, dtype: float64

In [85]:
df["Is_married"] = 0

In [86]:
df["Is_married"].loc[df["Title"] == "Mrs" ] = 1

C:\Users\kumar\AppData\Local\Temp\ipykernel_3788\858165026.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Is_married"].loc[df["Title"] == "Mrs" ] = 1

In [87]:
df["Is_married"].sample(5)

487    0
748    0
765    0
442    0
641    0
Name: Is_married, dtype: int64

In [91]:
df["Is_married"].value_counts()

Is_married
0    891
Name: count, dtype: int64